<GroupInfo>:
    GridLayout:
        rows: 2
        MDToolbar:
            id: toolbar
            title: "Group info"
            md_bg_color: app.theme_cls.primary_color
            background_palette: 'Primary'
            background_hue: '500'
            elevation: 10
            left_action_items: [['arrow-left', lambda x: root.on_back_pressed()]]

        GridLayout:
            id: grid
            cols: 1
